name: Update Version Files

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v3
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md

      - name: Extract Version from Tag
        id: extract_version
        run: |
          echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Update package.json
        run: |
          jq ".version = \"${{ env.version }}\"" package.json > package.tmp.json
          mv package.tmp.json package.json

      - name: Update README.md
        run: |
          sed "s/{{env.version}}/$version/g" README.md > README.tmp.md
          mv README.tmp.md README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json README.md CHANGELOG.md
          git commit -m "Update files version files"
          git push https://github.com/${{ github.repository }}.git HEAD:main