name: Update Version Files

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  update-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Extract Version from Tag
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Generate a simple changelog
        run: |
          echo "# Changelog" > CHANGELOG.md
          echo "" >> CHANGELOG.md
          git log $(git describe --tags --abbrev=0)^..HEAD --pretty=format:"- %s (%h)" >> CHANGELOG.md

      - name: Update package.json
        run: |
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ env.version }}\"/" package.json

      - name: Update README.md
        run: |
          sed "s/{{env.version}}/${{ env.version }}/g" README.md > README.tmp.md
          mv README.tmp.md README.md

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json README.md CHANGELOG.md
          git commit -m "Update version files"
          git push https://github.com/${{ github.repository }}.git HEAD:main